---
- name: Preparing Workstation
  hosts: all
  connection: local
  tasks:

    - name: Upgrade SO
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
    - name: Installing Linux Apps
      become: yes
      apt:
        install_recommends: yes
        state: present
        pkg:
            # - bat
            # - fzf
            # - qutebrowser
            - unzip
            - zstd
            - delta
            - aria2
            - blt-dev
            - cmake
            - curl
            - gettext
            - git
            - bash-completion
            - libbz2-dev
            - libfontconfig1-dev
            - libfreetype6-dev
            - libgdbm-dev
            - libncurses5-dev
            - libreadline-dev
            - libsqlite3-dev
            - libssl-dev
            - libxcb-xfixes0-dev
            - libxkbcommon-dev
            - llvm
            - pkg-config
            - python3-pip
            - python3
            - ranger
            - stow
            - tcl-dev
            - tk-dev
            - tmux
            - wget
            - zlib1g-dev
            - zsh
            - htop
            - jq

    - block:
      - name: Verify if Oh-My-zsh is installed
        command: test -d /home/{{ ansible_user_id }}/.oh-my-zsh
        register: ohmyzsh
        ignore_errors: yes
      - name: Installing Oh-My-zsh
        shell:
          cmd: 'curl -fsL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash'
          warn: no
        when: ohmyzsh.rc != 0
      - name: Changing Default Shell to ZSH
        become: yes
        user: 
          name: '{{ ansible_user_id }}'
          shell: /bin/zsh 
      - name: Changing Default ZSH Theme to Agnoster
        lineinfile:
          path: /home/{{ ansible_user_id }}/.zshrc
          regexp: '^ZSH_THEME='
          line: 'ZSH_THEME="robbyrussell"'
      - name: Creating ZSH Completion folder
        file:
          path: /home/{{ ansible_user_id }}/.oh-my-zsh/completions
          state: directory
          mode: 0755
      - name: Install ZSH syntax highlighting
        git:
          repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
          dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      - name: Adding autoload to compinit
        lineinfile:
          path: /home/{{ ansible_user_id }}/.zshrc
          line: 'autoload -U compinit && compinit'
          state: present
    - block:
      - name: Install Delta
        become: yes
        apt:
          deb: https://github.com/dandavison/delta/releases/download/0.8.3/git-delta_0.8.3_amd64.deb 
    - block:
      - name: Ensure fonts directory
        file:
          path: "{{ ansible_user_id }}/.fonts"
          state: directory
      - name: Hack exists
        shell: "ls {{ ansible_user_id }}/.fonts/Hack*Nerd*Font*Complete*"
        register: hack_exists
        ignore_errors: yes
      - name: Download Hack
        when: hack_exists is failed
        ansible.builtin.unarchive:
          src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
          dest: "{{ ansible_user_id }}/.fonts/"
          remote_src: yes
