---

- hosts: all
  connection: local
  gather_facts: yes
  roles:
    - role: roles/baseline
    - role: roles/languages
    - role: roles/terminal
    - role: roles/dotfiles
    - role: roles/flatpak
