_packages_base:
  all:
    - aria2
    - bash-completion
    - bat
    - exa
    - cargo
    - cmake
    - curl
    - direnv
    - flatpak
    - fzf
    - gettext
    - git
    - htop
    - i3
    - jq
    - llvm
    - pkg-config
    - polybar
    - python3
    - rofi
    - ranger
    - ripgrep
    - stow
    - tmux
    - unzip
    - wget
    - zsh
    - zstd

  Ubuntu:
    - blt-dev
    - delta
    - libbz2-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libgdbm-dev
    - libncurses5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxcb-xfixes0-dev
    - libxkbcommon-dev
    - python3-pip
    - tcl-dev
    - tk-dev
    - zlib1g-dev
    - meson 
    - asciidoc
    - libstartup-notification0-dev
    - libx11-xcb1
    - libxcb-xkb-dev
    - libxcb-xkb1
    - libxcb-xinerama0-dev
    - libxcb-randr0-dev
    - libxcb-shape0-dev
    - libxcb-util-dev
    - libxcb-cursor-dev
    - libxcb-keysyms1-dev
    - libxcb-icccm4-dev
    - libxcb-xrm-dev
    - librust-xkbcommon-dev
    - libxkbcommon-x11-dev
    - libyajl-dev
    - libpcre++-dev
    - libcairo2-dev
    - libpango1.0-dev
    - libpcre2-dev
    - libev-dev


  Archlinux:
    - bzip2
    - git-delta
    - fontconfig
    - freetype2
    - gdbm
    - ncurses
    - readline
    - sqlite
    - openssl
    - libxcb
    - libxkbcommon
    - python-pip
    - tcl
    - tk
    - zlib

packages_base: "{{ _packages_base['all'] + ( _packages_base[ansible_distribution] | default([]) ) }}"
