---
- name: ensure that deadd is installed
  command: test -d ~/.confg/deadd
  register: deadd_installed
  ignore_errors: yes
  tags:
    - deadd

- name: set configs to deadd
  file:
    src: "~/projects/dotfiles/deadd"
    dest: "~/.config/deadd"
    state: link
    force: yes
  when: deadd_installed.rc != 0
  tags:
    - deadd
    - deadd_config
