---
- name: last package of golang
  shell: wget -qO- https://golang.org/dl/ | grep -oP 'go([0-9.]+).linux-amd64.tar.gz' | head -n 1
  register: golang_last_package

- name: check if golang exist
  stat:
    path: /usr/local/go
  register: golang_avaliable

- name: remove old golang directory
  become: yes
  file: 
    path: /usr/local/go 
    state: absent
  when: golang_avaliable.stat.exists

- name: install last version of golang
  become: yes
  unarchive:
    src: "https://go.dev/dl/{{ golang_last_package.stdout }}"
    dest: /usr/local/
    remote_src: yes
