---
- name: check if golang exist
  stat:
    path: /usr/local/go
  register: golang_avaliable
  tags:
    - golang

- name: remove old golang directory
  become: yes
  file: 
    path: /usr/local/go 
    state: absent
  when: golang_avaliable.stat.exists
  tags:
    - golang

- name: install last version of golang
  become: yes
  unarchive:
    src: "https://go.dev/dl/go1.20.1.linux-amd64.tar.gz"
    dest: /usr/local/
    remote_src: yes
  tags:
    - golang
