---

- name: check if pyenv exist
  stat:
    path: ~/.pyenv/
  register: pyenv_avaliable

- name: remove pyenv directory
  file: 
    path: ~/.pyenv 
    state: absent
  when: pyenv_avaliable.stat.exists

- name: install pyenv
  shell: curl https://pyenv.run | bash

- name: install poetry
  shell: curl -sSL https://install.python-poetry.org | python3 -
